// <auto-generated />
using System;
using Demo1.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Demo1.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20201111021045_seeder_table_Users")]
    partial class seeder_table_Users
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Demo1.Models.Blog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<string>("Full_content")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Likes")
                        .HasColumnType("int");

                    b.Property<DateTime>("Publish_date")
                        .HasColumnType("datetime2");

                    b.Property<string>("Short_content")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Views")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.ToTable("Blogs");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CategoryId = 1,
                            Full_content = "Lorem Ipsum is simply dummy text of the printing and typesetting industry.",
                            ImageUrl = "https://img.lovepik.com/photo/50075/7988.jpg_wh860.jpg",
                            Likes = 0,
                            Publish_date = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Short_content = "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s",
                            Title = "Bảo Vệ Động Vật",
                            Views = 0
                        },
                        new
                        {
                            Id = 2,
                            CategoryId = 2,
                            Full_content = "Lorem Ipsum is simply dummy text of the printing and typesetting industry.",
                            ImageUrl = "https://img.lovepik.com/photo/50075/7988.jpg_wh860.jpg",
                            Likes = 0,
                            Publish_date = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Short_content = "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s",
                            Title = "Bảo Vệ Động Vật",
                            Views = 0
                        },
                        new
                        {
                            Id = 3,
                            CategoryId = 1,
                            Full_content = "Lorem Ipsum is simply dummy text of the printing and typesetting industry.",
                            ImageUrl = "https://img.lovepik.com/photo/50075/7988.jpg_wh860.jpg",
                            Likes = 0,
                            Publish_date = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Short_content = "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s",
                            Title = "Bảo Vệ Động Vật",
                            Views = 0
                        },
                        new
                        {
                            Id = 4,
                            CategoryId = 3,
                            Full_content = "Lorem Ipsum is simply dummy text of the printing and typesetting industry.",
                            ImageUrl = "https://img.lovepik.com/photo/50075/7988.jpg_wh860.jpg",
                            Likes = 0,
                            Publish_date = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Short_content = "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s",
                            Title = "Bảo Vệ Động Vật",
                            Views = 0
                        },
                        new
                        {
                            Id = 5,
                            CategoryId = 3,
                            Full_content = "Lorem Ipsum is simply dummy text of the printing and typesetting industry.",
                            ImageUrl = "https://img.lovepik.com/photo/50075/7988.jpg_wh860.jpg",
                            Likes = 0,
                            Publish_date = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Short_content = "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s",
                            Title = "Bảo Vệ Động Vật",
                            Views = 0
                        });
                });

            modelBuilder.Entity("Demo1.Models.BlogTag", b =>
                {
                    b.Property<int>("BlogId")
                        .HasColumnType("int");

                    b.Property<int>("TagId")
                        .HasColumnType("int");

                    b.HasKey("BlogId", "TagId");

                    b.HasIndex("TagId");

                    b.ToTable("BlogTag");
                });

            modelBuilder.Entity("Demo1.Models.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("CategoryName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CategoryName = "Travel"
                        },
                        new
                        {
                            Id = 2,
                            CategoryName = "Product"
                        },
                        new
                        {
                            Id = 3,
                            CategoryName = "Resaurant food"
                        });
                });

            modelBuilder.Entity("Demo1.Models.Tag", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Tags");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Rẻ"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Ngon"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Bổ Khỏe"
                        });
                });

            modelBuilder.Entity("Demo1.Models.Blog", b =>
                {
                    b.HasOne("Demo1.Models.Category", "Category")
                        .WithMany("Blogs")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Demo1.Models.BlogTag", b =>
                {
                    b.HasOne("Demo1.Models.Blog", "Blog")
                        .WithMany("BlogTags")
                        .HasForeignKey("BlogId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Demo1.Models.Tag", "Tag")
                        .WithMany("BlogTags")
                        .HasForeignKey("TagId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
